title:            Payssion
description:      一站式全球收款解决方案
url:              https://www.payssion.com
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          payssion # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.

links:
  - name:         Payssion首页
    url:          https://www.payssion.com
    external:     true
  - name:         全球收款解决方案
    url:          https://payssion.com/cn/globalpayments.html
    external:     true
  - name:         关于我们
    url:          https://payssion.com/cn/about.html
    external:     true
  - name:         Blog
    url:          /

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
